### ISSUE TITLE
Error when running telescope assign

### ISSUE THREAD

**Issue by jalalsiddiqui** [mlbendall/telescope#15]
I tried to run telescope assign on one of my alignment files and get the following lines:

Traceback (most recent call last):
  File "/users/PAS1143/osu8165/.conda/envs/telescope_env/bin/telescope", line 11, in <module>
    load_entry_point('telescope-ngs==1.0.3', 'console_scripts', 'telescope')()
  File "/users/PAS1143/osu8165/.conda/envs/telescope_env/lib/python3.6/site-packages/telescope/__main__.py", line 95, in main
    args.func(args)
  File "/users/PAS1143/osu8165/.conda/envs/telescope_env/lib/python3.6/site-packages/telescope/telescope_assign.py", line 216, in run
    ts.load_alignment(annot)
  File "/users/PAS1143/osu8165/.conda/envs/telescope_env/lib/python3.6/site-packages/telescope/utils/model.py", line 161, in load_alignment
    maps, scorerange, alninfo = self._load_sequential(annotation)
  File "/users/PAS1143/osu8165/.conda/envs/telescope_env/lib/python3.6/site-packages/telescope/utils/model.py", line 250, in _load_sequential
    _minAS = min(_minAS, *_scores)
TypeError: 'int' object is not iterable

**Comment by olferievm** [comment]
Have a similar issue. After installation telescope -test works fine. When using the actual bam file got an error:
  File "/Users/olferievm/NGSTools/Telescope/venv/bin/telescope", line 8, in <module>
    sys.exit(main())
  File "/Users/olferievm/NGSTools/Telescope/venv/lib/python3.8/site-packages/telescope/__main__.py", line 95, in main
    args.func(args)
  File "/Users/olferievm/NGSTools/Telescope/venv/lib/python3.8/site-packages/telescope/telescope_assign.py", line 216, in run
    ts.load_alignment(annot)
  File "/Users/olferievm/NGSTools/Telescope/venv/lib/python3.8/site-packages/telescope/utils/model.py", line 164, in load_alignment
    self._mapping_to_matrix(maps, scorerange, alninfo)
  File "/Users/olferievm/NGSTools/Telescope/venv/lib/python3.8/site-packages/telescope/utils/model.py", line 300, in _mapping_to_matrix
    for code, rid, fid, ascr, alen in miter:
  File "/Users/olferievm/NGSTools/Telescope/venv/lib/python3.8/site-packages/telescope/utils/model.py", line 211, in _mapping_fromfiles
    yield (int(code), rid, fid, int(ascr), int(alen))
ValueError: invalid literal for int() with base 10: 'cached'

bam file has been prepared using STAR aligner and indexed by coordinate.

**Comment by olferievm** [comment]
telescope assign --ncpu 4 /Users/olferievm/NGSTools/Telescope/IF_0141V06.chr19.sorted.bam  transcripts.gtf

It seems the multithreading parameter --ncpu 4 caused the problem. The manual said that multithreading is not supported yet.

**Comment by AndrewRosato** [comment]
I've run into the same (TypeError: 'int' object is not iterable" ) error as jalalsiddiqui and believe I may have another potential solution. I have only observed the problem occur while aligning paired-end sequencing data, both regular unpaired aligned SAM files and aligned SAM files created by only aligning one-half of paired ended data run through Telescope without this error occurring. 
I believe the error occurs because of the formatting of the paired-end reads, aligned reads with the readname/2 or readname/1 format do not cause the error to appear. While aligned reads with the readname.1 or readname.2 format do cause the error. 
Fastq files with reads in the /1 /2 format can be downloaded directly from the ENA by searching for the SRR number of the desired samples. 
I have attached examples of data from aligned SAM files and have indicated whether the SAM file produced an error or successfully ran through Telescope. 
[sam_example.txt](https://github.com/mlbendall/telescope/files/6016449/sam_example.txt)

**Comment by AssumeAssume** [comment]
> telescope assign --ncpu 4 /Users/olferievm/NGSTools/Telescope/IF_0141V06.chr19.sorted.bam transcripts.gtf
> 
> It seems the multithreading parameter --ncpu 4 caused the problem. The manual said that multithreading is not supported yet.

Thanks, @olferievm , removing the `--ncpu x` solves my problem.

**Comment by gigimath** [comment]
Hi everybody,
I run telescope successfully on my bams. I had your same issue, but I figured it out filtering my bams taking only chr1 chr2... chr22 chrX chrY. So I removed the "contig" parts and it is working fine now. I removed the "contig" also from the GTF file, they are the lines after the ChrY.
Of course remember to not use the "--ncpu x" in the command because it looks like it is not supported.
Greetings

**Comment by rodrigoduarte88** [comment]
I am reading through this thread but still not sure how to fix the error. I am not invoking multithreading, I've removed HERVs located outside of autosomes from the GTF file and from the BAM file from bowtie2, and yet this problem persists :(

**Comment by shizhiwen1990** [comment]
Add "--ncpu 4 ", solves my problem.

**Comment by JianhuaWang95** [comment]
Have you guys sort the bam files before using telescope?

**Comment by MDisyak** [comment]
One solution I found was to use the files in SAM format.  For some reason the BAM (even properly sorted) would throw this error.  It's possible it is related to the sorting in some way, but the original SAM runs fine.  Will update if I find out any more specifics.

**Comment by AnnalisaTuninetti** [comment]
I am encountering this problem as well with some of my files, I've tried using .sam format instead of .sam, and I'm not invoking multithreading, but no luck.

**Comment by AnnalisaTuninetti** [comment]
> Have you guys sort the bam files before using telescope?

I have sorted them and trimmed them, the problem persists
