### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'Interval'

### ISSUE THREAD

**Issue by zya226** [mlbendall/telescope#19]
Hi mlbendall,

I had a problem when I was running telescope. Could you please let me know how to solve it? 

 (from run in telescope_assign.py:197)
2021-02-11 01:21:50 INFO     Loading annotation...                                        (from run in telescope_assign.py:205)
Traceback (most recent call last):
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/lib/python3.6/site-packages/intervaltree/intervaltree.py", line 1039, in __getitem__
    start, stop = index.start, index.stop
AttributeError: 'Interval' object has no attribute 'start'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/bin/telescope", line 11, in <module>
    sys.exit(main())
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/lib/python3.6/site-packages/telescope/__main__.py", line 58, in main
    args.func(args)
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/lib/python3.6/site-packages/telescope/telescope_assign.py", line 207, in run
    annot = Annotation(opts.gtffile, opts.attribute)
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/lib/python3.6/site-packages/telescope/utils/_annotation_intervaltree.py", line 48, in __init__
    overlap = self.itree[f.chrom][new_iv]
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/lib/python3.6/site-packages/intervaltree/intervaltree.py", line 1048, in __getitem__
    return self.at(index)
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/lib/python3.6/site-packages/intervaltree/intervaltree.py", line 800, in at
    return root.search_point(p, set())
  File "/usr/local/Anaconda/envs_app/telescope/1.0.2/lib/python3.6/site-packages/intervaltree/node.py", line 297, in search_point
    if k.begin <= point < k.end:
TypeError: '<=' not supported between instances of 'int' and 'Interval'

Thanks,
Yong

**Comment by sanhe374** [comment]
I get the same error when running telescope and would like help on how to solve this issue.
