### ISSUE TITLE
Install Telescope with Miniconda3

### ISSUE THREAD

**Issue by YangpingLi** [mlbendall/telescope#27]
Hi,

I'm trying to install telescope by miniconda3 following the instruction. The command I used was:

**conda create -n telescope
conda activate telescope
conda install -c bioconda telescope**

Everything went fine till here.

Then I tried:

**telescope bulk test**

The error message was:

Traceback (most recent call last):
  File "/projects/compbio/users/byao5/miniconda3/envs/telescope/bin/telescope", line 7, in <module>
    from telescope.__main__ import main
  File "/projects/compbio/users/byao5/miniconda3/envs/telescope/lib/python3.9/site-packages/telescope/__main__.py", line 14, in <module>
    from . import telescope_assign
  File "/projects/compbio/users/byao5/miniconda3/envs/telescope/lib/python3.9/site-packages/telescope/telescope_assign.py", line 22, in <module>
    from .utils.model import Telescope, TelescopeLikelihood
  File "/projects/compbio/users/byao5/miniconda3/envs/telescope/lib/python3.9/site-packages/telescope/utils/model.py", line 22, in <module>
    from . import alignment
  File "/projects/compbio/users/byao5/miniconda3/envs/telescope/lib/python3.9/site-packages/telescope/utils/alignment.py", line 15, in <module>
    from telescope.utils.calignment import AlignedPair
  File "telescope/utils/calignment.pyx", line 1, in init telescope.utils.calignment
AttributeError: module 'pysam.libcalignmentfile' has no attribute 'PileupColumn'

Could you please help with this issue?

Thanks so much!

Yangping

**Comment by Rohak72** [comment]
Hi,

I was wondering how you solved this issue! Dealing with it right now, so any help/advice would be greatly appreciated. Thanks!
