### ISSUE TITLE
Installation to high performance computing cluster failing

### ISSUE THREAD

**Issue by guypwhunt** [mlbendall/telescope#46]
Hi 

I have been trying to install the latest version of telescope to my high performance computing cluster but the installation keeps failing.

When I try to install it via conda using the following command:
`conda install -c bioconda telescope`

I get this error:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): \ Killed
```

When I try to install it via pip using the following command:
`pip install git+https://github.com/mlbendall/telescope.git`

I get this error:
```
Collecting git+https://github.com/mlbendall/telescope.git
  Cloning https://github.com/mlbendall/telescope.git to /tmp/pip-req-build-ope17xrm
  Running command git clone --filter=blob:none --quiet https://github.com/mlbendall/telescope.git /tmp/pip-req-build-ope17xrm
  Resolved https://github.com/mlbendall/telescope.git to commit 4cf18595eea1702775e8a8bbc7b37ebac9233fd5
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /users/k20064105/mambaforge/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-req-build-ope17xrm/telescope/utils/calignment.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # -*- coding: utf-8 -*-
      from calignment cimport AlignedPair
      ^
      ------------------------------------------------------------

      telescope/utils/calignment.pyx:2:0: 'calignment.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # -*- coding: utf-8 -*-
      from calignment cimport AlignedPair
      ^
      ------------------------------------------------------------

      telescope/utils/calignment.pyx:2:0: 'calignment/AlignedPair.pxd' not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-ope17xrm/setup.py", line 39, in <module>
          extensions = cythonize(extensions)
        File "/users/k20064105/mambaforge/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/users/k20064105/mambaforge/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: telescope/utils/calignment.pyx
      Compiling telescope/utils/calignment.pyx because it changed.
      [1/1] Cythonizing telescope/utils/calignment.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

Thanks for all your help in advance.

Guy

**Comment by Rohak72** [comment]
Hi,

Did you ever figure out how to solve this? Actually dealing with the same issue right now, so wanted to see if you had any fixes. Thanks!

**Comment by guypwhunt** [comment]
@Rohak72 yeah.

I eventually found out it was a memory issue when trying to install telescope and its dependencies.

So I got around it by requesting a tonne of memory and then installing it.

**Comment by peterwu19881230** [comment]
How much RAM is needed for that error to not occur? I also get the same error on AWS EC2 fom an Ubuntu machine (RAM: 64G). I also noticed that the installed cython version is 3.0.3. Is that a compatible version? I tried downgrading but other complications happened. Thanks.

`calignment.pxd` is currently under `telescope/telescope/utils`

**Comment by guypwhunt** [comment]
I am not sure how much RAM it required, I probably either used 50GB or 100GB as that is what I typically use. But I assume it shouldn't require that much. I have no idea about the cython version.

**Comment by murphytho** [comment]
Hi @peterwu19881230 

Did you ever find a way around this? I'm running into the same error on a machine of similar specs. I tried downgrading cython, but it didn't work. 

Thanks!
