### ISSUE TITLE
KeyError: 'nunmap_idx'

### ISSUE THREAD

**Issue by thejustpark** [mlbendall/telescope#5]
I installed this packaged based on telescope documentation ( https://github.com/mlbendall/telescope )

python=3.6 numpy=1.13 scipy=0.19.0 pysam=0.12 cython intervaltree

It seems that intervaltree is updated to version 3.0.2 during Dec. 2018, and this version generates problems. I have downgraded it to version 2.1.0.

intervaltree problems are solved. However, I find a new problem.

[fangping@login0b telescope_debug]$ telescope assign outRABT_BT_S1Aligned.out.bam transcripts.gtf --outdir ./RABT_BT_S1
/ihome/crc/install/telescope/python3.7/lib/python3.6/site-packages/telescope/utils/__init__.py:62: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
for grp in yaml.load(opts_yaml):
2019-05-06 19:15:42 INFO
Version: 1.0.2
Input Options
samfile: outRABT_BT_S1Aligned.out.bam
gtffile: transcripts.gtf
attribute: locus
no_feature_key: __no_feature
ncpu: 1
tempdir: None
Reporting Options
quiet: False
debug: False
logfile: <stderr>
outdir: ./RABT_BT_S1
exp_tag: telescope
updated_sam: False
Run Modes
reassign_mode: exclude
conf_prob: 0.9
overlap_mode: threshold
overlap_threshold: 0.2
annotation_class: intervaltree
Model Parameters
pi_prior: 0
theta_prior: 200000
em_epsilon: 1e-07
max_iter: 100
use_likelihood: False
skip_em: False
(from run in telescope_assign.py:197)
2019-05-06 19:15:42 INFO Loading annotation... (from run in telescope_assign.py:205)
2019-05-06 19:15:49 INFO Loaded annotation in 0 minutes and 6 secs (from run in telescope_assign.py:208)
2019-05-06 19:15:49 INFO Loaded 14896 features. (from run in telescope_assign.py:209)
2019-05-06 19:15:49 INFO Loading alignments... (from run in telescope_assign.py:214)
Traceback (most recent call last):
File "/ihome/crc/install/telescope/python3.7/bin/telescope", line 10, in <module>
sys.exit(main())
File "/ihome/crc/install/telescope/python3.7/lib/python3.6/site-packages/telescope/__main__.py", line 58, in main
args.func(args)
File "/ihome/crc/install/telescope/python3.7/lib/python3.6/site-packages/telescope/telescope_assign.py", line 216, in run
ts.load_alignment(annot)
File "/ihome/crc/install/telescope/python3.7/lib/python3.6/site-packages/telescope/utils/model.py", line 164, in load_alignment
self._mapping_to_matrix(maps, scorerange, alninfo)
File "/ihome/crc/install/telescope/python3.7/lib/python3.6/site-packages/telescope/utils/model.py", line 308, in _mapping_to_matrix
unmap_both = self.run_info['nunmap_idx'] - alninfo['unmap_x']
KeyError: 'nunmap_idx'

**Comment by mlbendall** [comment]
Thanks for reporting these issues. Telescope now supports intervaltree v3.0.2, and I've resolved the KeyError exception.
