### ISSUE TITLE
telescope installation

### ISSUE THREAD

**Issue by fatemehkordevani** [mlbendall/telescope#51]
I have been receiving the following error, and I don't seem to be able to find a solution for it on macOS. Any help and guidance will be very much appreciated. 
'''
$ pip install Downloads/telescope-main
Processing ./Downloads/telescope-main
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      /Users/kordevani.fatemeh/miniconda3/envs/telescope/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /Users/myuser/Downloads/telescope-main/telescope/utils/calignment.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # -*- coding: utf-8 -*-
      from calignment cimport AlignedPair
      ^
      ------------------------------------------------------------
      
      telescope/utils/calignment.pyx:2:0: 'calignment.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # -*- coding: utf-8 -*-
      from calignment cimport AlignedPair
      ^
      ------------------------------------------------------------
      
      telescope/utils/calignment.pyx:2:0: 'calignment/AlignedPair.pxd' not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/myuser/Downloads/telescope-main/setup.py", line 39, in <module>
          extensions = cythonize(extensions)
                       ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/myuser/miniconda3/envs/telescope/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/Users/myuser/miniconda3/envs/telescope/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: telescope/utils/calignment.pyx
      Compiling telescope/utils/calignment.pyx because it changed.
      [1/1] Cythonizing telescope/utils/calignment.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
'''

**Comment by murphytho** [comment]
Hi there, did you ever find a solution here? I've had Telescope installed fine in the past, but I run into this when trying to install with pip.
Thanks!

**Comment by marcos-da-conceicao** [comment]
Here is a comment I made solving the problem. [link](https://github.com/mlbendall/telescope/issues/57#issuecomment-3165288074)
