### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'cached'

### ISSUE THREAD

**Issue by nongbaoting** [mlbendall/telescope#9]
I have encountered an error when running telescope. could you please help me? thanks.
```
Traceback (most recent call last):
  File "/dsk2/who/nbt/miniconda3/envs/telescope_env/bin/telescope", line 8, in <module>
    sys.exit(main())
  File "/dsk2/who/nbt/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/__main__.py", line 95,
in main
    args.func(args)
  File "/dsk2/who/nbt/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/telescope_assign.py", l
ine 216, in run
    ts.load_alignment(annot)
  File "/dsk2/who/nbt/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/utils/model.py", line 1
64, in load_alignment
    self._mapping_to_matrix(maps, scorerange, alninfo)
  File "/dsk2/who/nbt/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/utils/model.py", line 3
00, in _mapping_to_matrix
    for code, rid, fid, ascr, alen in miter:
  File "/dsk2/who/nbt/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/utils/model.py", line 2
11, in _mapping_fromfiles
    yield (int(code), rid, fid, int(ascr), int(alen))
ValueError: invalid literal for int() with base 10: 'cached'

```

**Comment by savytskanatalia** [comment]
I have same error...
@nongbaoting , did you manage to resolve this error?
Command I used:

` telescope assign STAR_out/multi_genome_only/sample01_go_multi_sorted.bam GTF/mod_repmsk_mm9_tele.gtf --ncpu 20 --tempdir telescope/ --outdir telescope/`

It seems, the process initializes, I get the message:

> 2020-01-28 12:54:23 INFO     Loading annotation...                                        (from run in telescope_assign.py:205)
> 2020-01-28 13:02:24 INFO     Loaded annotation in 8 minutes and 1 secs                    (from run in telescope_assign.py:208)
> 2020-01-28 13:02:24 INFO     Loaded 3456767 features.                                     (from run in telescope_assign.py:209)
> 2020-01-28 13:02:24 INFO     Loading alignments...                                        (from run in telescope_assign.py:214)
> 2020-01-28 13:02:35 INFO     Loading alignments in parallel...                            (from _load_parallel in model.py:175)

But after alignments to all chromosomes are loaded, Telescope shoots the "ValueError: invalid literal for int() with base 10: 'cached'"....

**Comment by wangliying235** [comment]
@savytskanatalia @nongbaoting 
Have you solved the problem?  I have identical issue. Would you like to share your solution?

**Comment by savytskanatalia** [comment]
> @savytskanatalia @nongbaoting
> Have you solved the problem? I have identical issue. Would you like to share your solution?

No, I just switched altogether to TElocal by Hammel`s Lab.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
I also have the same problem...

**Comment by flatychen** [comment]
Hi , This issue because you may be use the  --ncpu NCPU    , but it can not support now . I have solved this problem by remove the npcu parameter.
